
logging:
  level: INFO
  loggers:
    com.github.behooked.administration: DEBUG
    
database:

  driverClass: org.postgresql.Driver
   
  
  user: lisa
  password: sUuupAsiCr6t
  
  url: jdbc:postgresql:administration

  properties:
    hibernate.hbm2ddl.auto: create
    
server:

  applicationConnectors:
    - type: http
      port: 8085

  adminConnectors:
    - type: http
      port: 8081    
    
    
