logging:
  level: INFO
  loggers:
    com.github.behooked.administration: DEBUG
    
database:

  driverClass: org.postgresql.Driver

  user: schindler
  password: sUuupAsiCr6t

  url: jdbc:postgresql:webhooks

  properties:
    hibernate.hbm2ddl.auto: create